### PR TITLE
Port 'clojure.zip' #2

### PR DESCRIPTION
**Pull request by ruseel**
second try after #151.

only [s/clojure.zip/cljd.zip/](https://github.com/Tensegritics/ClojureDart/commit/2171b169baba7fa872a9c20e1877b0d18d918a7b) ❤️

### CODE REVIEW

**Comment by cgrand** [comment]
Would you be kind enough to also port tests covering zip?

**Comment by ruseel** [comment]
There is almose empty ns `clojure.test-clojure.clojure-zip` in clojure/clojure. [clojure_zip.clj](https://github.com/clojure/clojure/blob/master/test/clojure/test_clojure/clojure_zip.clj)

So I should create some.
I am not guessing that cgrand would want me to create new test. 

But if you want, I would love to do that.

**Comment by ruseel** [comment]
hmm, I will work on adding same test on both clojure/clojure and clojuredart.

**Comment by dupuchba** [comment]
@ruseel that would be awesome - keep it simple !
To do that you can use Rich's comments.

Steps to create tests : 
- create a ns here     cljd.test-clojure.zip
- add to `run-tests` file your `ns` here 
```(ns ci.core
  (:require
    cljd.test-clojure.core-test-cljd
    cljd.test-clojure.string
    cljd.test-clojure.core-test
    cljd.test-clojure.for
    cljd.test-reader.reader-test))```
make them pass by running `run-tests`

**Comment by ruseel** [comment]
`./run-tests` worked for me. 

edited (clojure_zip.clj from clojure/clojure). 
not sure that was a good choice.

**Comment by ruseel** [comment]
Outside of this PR, I created request to make a JIRA account in CLJ.
But I think It would be hard for me to make a good ticket. 
At least I will try to make ticket in CLJ, too.

**Comment by dupuchba** [comment]
Thanks a lot @ruseel !

**Pull request merged**
